import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import {
  parseDishes,
  parseIngredients,
  parseMenuHistory,
} from "../src/data/parse.js";
import {
  validateMenuHistoryAgainstLibrary,
  validatePackSizesUsed,
} from "../src/data/validators.js";
import type {
  Dish,
  Ingredient,
  MenuHistoryRow,
  PackSizeHeader,
} from "../src/data/schemas.js";

// Dish ids referenced by data/menu_history.md but not yet present in
// data/dishes.md. Tracked as open item 13 in features/phase2.md §5 (Rajma,
// dish id 7). Remove an id once the corresponding row lands in the dish
// library; remove the whole set when the open item is resolved.
const KNOWN_MISSING_DISH_IDS = new Set<number>([7]);

interface BakeOutput {
  libraryPath: string;
  historyPath: string;
  dishCount: number;
  ingredientCount: number;
  packSizeCount: number;
  historyRowCount: number;
}

interface BakeOptions {
  dataDir: string;
  outDir: string;
}

function tsLiteral(value: unknown): string {
  return JSON.stringify(value);
}

function renderLibrary(
  dishes: Dish[],
  packSizes: PackSizeHeader[],
  ingredients: Ingredient[],
): string {
  return [
    "// Generated by engine/scripts/bake.ts from data/*.md. Do not edit by hand.",
    "",
    'import type {',
    "  Dish,",
    "  Ingredient,",
    "  PackSizeHeader,",
    '} from "./schemas.js";',
    "",
    `export const dishes: Dish[] = ${tsLiteral(dishes)};`,
    "",
    `export const packSizes: PackSizeHeader[] = ${tsLiteral(packSizes)};`,
    "",
    `export const ingredients: Ingredient[] = ${tsLiteral(ingredients)};`,
    "",
    "export const library: {",
    "  dishes: Dish[];",
    "  packSizes: PackSizeHeader[];",
    "  ingredients: Ingredient[];",
    "} = { dishes, packSizes, ingredients };",
    "",
  ].join("\n");
}

function renderHistory(rows: MenuHistoryRow[]): string {
  return [
    "// Generated by engine/scripts/bake.ts from data/*.md. Do not edit by hand.",
    "",
    'import type { MenuHistoryRow } from "./schemas.js";',
    "",
    `export const history: MenuHistoryRow[] = ${tsLiteral(rows)};`,
    "",
  ].join("\n");
}

export function bake(options: BakeOptions): BakeOutput {
  const { dataDir, outDir } = options;

  const dishesMd = readFileSync(resolve(dataDir, "dishes.md"), "utf8");
  const ingredientsMd = readFileSync(
    resolve(dataDir, "ingredients.md"),
    "utf8",
  );
  const historyMd = readFileSync(resolve(dataDir, "menu_history.md"), "utf8");

  const dishes = parseDishes(dishesMd);
  const { packSizes, rows: ingredients } = parseIngredients(ingredientsMd);
  const history = parseMenuHistory(historyMd);

  validatePackSizesUsed(packSizes, ingredients);

  const filteredHistory = history.filter(
    (r) => !KNOWN_MISSING_DISH_IDS.has(r.dishId),
  );
  validateMenuHistoryAgainstLibrary(filteredHistory, dishes);

  const libraryPath = resolve(outDir, "library.ts");
  const historyPath = resolve(outDir, "history.ts");

  writeFileSync(libraryPath, renderLibrary(dishes, packSizes, ingredients));
  writeFileSync(historyPath, renderHistory(history));

  return {
    libraryPath,
    historyPath,
    dishCount: dishes.length,
    ingredientCount: ingredients.length,
    packSizeCount: packSizes.length,
    historyRowCount: history.length,
  };
}

function defaultPaths(): BakeOptions {
  const here = dirname(fileURLToPath(import.meta.url));
  // When compiled, this file lives at engine/dist/scripts/bake.js, so the
  // repo root is three levels up. Resolve the source dir for output (not the
  // dist mirror) so the emitted files land where the rest of the engine
  // imports them.
  const repoRoot = resolve(here, "../../..");
  return {
    dataDir: resolve(repoRoot, "data"),
    outDir: resolve(repoRoot, "engine/src/data"),
  };
}

function isEntrypoint(): boolean {
  if (!process.argv[1]) return false;
  try {
    return resolve(process.argv[1]) === fileURLToPath(import.meta.url);
  } catch {
    return false;
  }
}

if (isEntrypoint()) {
  try {
    const result = bake(defaultPaths());
    process.stdout.write(
      [
        `bake: wrote ${result.libraryPath}`,
        `bake: wrote ${result.historyPath}`,
        `bake: ${result.dishCount} dishes, ${result.packSizeCount} pack sizes, ${result.ingredientCount} ingredient rows, ${result.historyRowCount} history rows`,
        "",
      ].join("\n"),
    );
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    process.stderr.write(`bake failed: ${message}\n`);
    process.exit(1);
  }
}
