import { mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { combinedSeedHistory, loadLibrary } from "../src/loadData.js";
import { runSimulation } from "../src/simulate.js";
import type { FavoriteInput, Incident, Pick, WeekPlan } from "../src/types.js";

/**
 * Writes the four simulation artefacts. Pure output: nothing here touches Convex,
 * `data/`, or any deployment.
 *
 * Usage: node proto-v4/dist/proto-v4/scripts/run-simulation.js <outDir> <archiveJson>
 */

const START_WEEK = "2026-08-17";
const WEEK_COUNT = 25;

/** The real prod favorites table: exactly one row, dish 273 (Avocado toast), no dial. */
const PRIMARY_FAVORITES: FavoriteInput[] = [{ dishId: 273 }];

/** A plausible set that actually exercises the `timesPerWeek` dial. */
const VARIANT_FAVORITES: FavoriteInput[] = [
  { dishId: 273 }, // Avocado toast (breakfast)
  { dishId: 118, timesPerWeek: 2 }, // Fish tikka, dialed to twice a week
  { dishId: 30 }, // Boiled eggs (breakfast)
  { dishId: 8 }, // Kadhi (lunch companion)
  { dishId: 113 }, // Grilled chicken breast (lunch)
];

interface ItemOut {
  dishId: number;
  name: string;
  category: string;
  tags: string[];
  cuisine: string;
  primaryIngredient: string;
  role: string;
}

function itemOut(pick: Pick): ItemOut {
  return {
    dishId: pick.dish.id,
    name: pick.dish.name,
    category: pick.dish.category,
    tags: pick.dish.tags,
    cuisine: pick.dish.cuisine,
    primaryIngredient: pick.dish.primaryIngredient,
    role: pick.role,
  };
}

function weeksOut(weeks: WeekPlan[], label: string, favorites: FavoriteInput[]): unknown {
  return {
    run: label,
    generator: "engine/proto-v4 (throwaway prototype of features/engine-v4.md)",
    startWeek: START_WEEK,
    weekCount: WEEK_COUNT,
    favorites,
    roleVocabulary: [
      "protein-main",
      "carb",
      "companion",
      "protein-floor",
      "breakfast-main",
      "breakfast-accompaniment",
      "dessert",
      "fruit",
      "exploration",
    ],
    weeks: weeks.map((w) => ({
      weekStart: w.weekStart,
      season: w.season,
      days: w.days.map((d) => ({
        day: d.day,
        date: d.date,
        itemCount: d.breakfast.length + d.lunch.length,
        fruit: d.fruit ? itemOut(d.fruit) : null,
        breakfast: d.breakfast.map(itemOut),
        lunch: d.lunch.map(itemOut),
      })),
    })),
  };
}

function weeksMarkdown(weeks: WeekPlan[], label: string, favorites: FavoriteInput[]): string {
  const lines: string[] = [];
  lines.push(`# Engine v4 prototype simulation, ${label}`);
  lines.push("");
  lines.push(
    `${WEEK_COUNT} consecutive weeks from ${START_WEEK}. Generated by \`engine/proto-v4\`, a throwaway prototype of \`features/engine-v4.md\`. No swaps, no skipped days, no requests: this is the engine's unaided output.`,
  );
  lines.push("");
  lines.push(
    `Favorites input: ${favorites
      .map(
        (f) => `${f.dishId}${f.timesPerWeek && f.timesPerWeek > 1 ? ` (x${f.timesPerWeek})` : ""}`,
      )
      .join(", ")}`,
  );
  lines.push("");

  const fmt = (p: Pick): string => `${p.dish.name} _(${p.role})_`;

  for (const w of weeks) {
    lines.push(`## Week of ${w.weekStart} (${w.season})`);
    lines.push("");
    for (const d of w.days) {
      const count = d.breakfast.length + d.lunch.length;
      lines.push(`### ${d.day} ${d.date} (${count} items)`);
      lines.push("");
      lines.push(`- Fruit: ${d.fruit ? d.fruit.dish.name : "none"}`);
      lines.push(`- Breakfast: ${d.breakfast.length ? d.breakfast.map(fmt).join(", ") : "none"}`);
      lines.push(`- Lunch: ${d.lunch.length ? d.lunch.map(fmt).join(", ") : "none"}`);
      lines.push("");
    }
  }
  return lines.join("\n");
}

function incidentsOut(primary: Incident[], variant: Incident[]): unknown {
  const summarise = (list: Incident[]): Record<string, number> => {
    const byKind: Record<string, number> = {};
    for (const i of list) byKind[i.kind] = (byKind[i.kind] ?? 0) + 1;
    return byKind;
  };
  return {
    generator: "engine/proto-v4 (throwaway prototype of features/engine-v4.md)",
    summary: {
      primary: { total: primary.length, byKind: summarise(primary) },
      variant: { total: variant.length, byKind: summarise(variant) },
    },
    primary,
    variant,
  };
}

function main(): void {
  const outDir = process.argv[2];
  const archiveJson = process.argv[3];
  if (!outDir || !archiveJson) {
    throw new Error("usage: run-simulation <outDir> <archiveHistoryJson>");
  }
  mkdirSync(outDir, { recursive: true });

  const library = loadLibrary();
  const seedHistory = combinedSeedHistory(archiveJson);

  const primary = runSimulation({
    library,
    seedHistory,
    startWeek: START_WEEK,
    weekCount: WEEK_COUNT,
    favorites: PRIMARY_FAVORITES,
  });
  const variant = runSimulation({
    library,
    seedHistory,
    startWeek: START_WEEK,
    weekCount: WEEK_COUNT,
    favorites: VARIANT_FAVORITES,
  });

  writeFileSync(
    resolve(outDir, "weeks-primary.json"),
    `${JSON.stringify(weeksOut(primary.weeks, "primary", PRIMARY_FAVORITES), null, 2)}\n`,
  );
  writeFileSync(
    resolve(outDir, "weeks-variant.json"),
    `${JSON.stringify(weeksOut(variant.weeks, "variant", VARIANT_FAVORITES), null, 2)}\n`,
  );
  writeFileSync(
    resolve(outDir, "weeks-primary.md"),
    `${weeksMarkdown(primary.weeks, "primary run (real prod favorites: dish 273 only)", PRIMARY_FAVORITES)}\n`,
  );
  writeFileSync(
    resolve(outDir, "weeks-variant.md"),
    `${weeksMarkdown(variant.weeks, "variant run (five favorites, fish tikka dialed to 2)", VARIANT_FAVORITES)}\n`,
  );
  writeFileSync(
    resolve(outDir, "incidents.json"),
    `${JSON.stringify(incidentsOut(primary.incidents, variant.incidents), null, 2)}\n`,
  );

  process.stdout.write(
    `wrote ${primary.weeks.length} primary weeks and ${variant.weeks.length} variant weeks to ${outDir}\n` +
      `primary incidents: ${primary.incidents.length}, variant incidents: ${variant.incidents.length}\n`,
  );
}

main();
