import { describe, it, expect, beforeEach, afterAll } from "vitest";
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { tmpdir } from "node:os";
import { bake } from "../../scripts/bake.js";
import { loadDishFiles } from "../../scripts/bake.js";
import { parseMenuHistory } from "../../src/data/parse.js";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "../../..");
const liveDataDir = resolve(repoRoot, "data");
const liveOutDir = resolve(repoRoot, "engine/src/data");

function cleanLiveOutputs(): void {
  for (const file of ["library.ts", "history.ts"]) {
    const p = resolve(liveOutDir, file);
    if (existsSync(p)) rmSync(p);
  }
}

describe("bake against live data", () => {
  beforeEach(() => {
    cleanLiveOutputs();
  });
  afterAll(() => {
    cleanLiveOutputs();
  });

  it("emits library.ts with matching counts, and counts the history rows it validated", () => {
    const result = bake({ dataDir: liveDataDir, outDir: liveOutDir });

    expect(existsSync(result.libraryPath)).toBe(true);

    const libraryText = readFileSync(result.libraryPath, "utf8");

    expect(
      libraryText.startsWith(
        "// Generated by engine/scripts/bake.ts from data/dishes/*.md + data/ingredients.md. Do not edit by hand.",
      ),
    ).toBe(true);

    const dishFiles = loadDishFiles(resolve(liveDataDir, "dishes"));
    expect(result.dishCount).toBe(dishFiles.length);

    const history = parseMenuHistory(readFileSync(resolve(liveDataDir, "menu_history.md"), "utf8"));
    expect(result.historyRowCount).toBe(history.length);
  });

  it("does not emit history.ts: v6 retired the seed history as a signal", () => {
    // `features/engine-v6.md` §13. `data/menu_history.md` stays in the repo for
    // provenance and is still validated against the library (the case below), but
    // nothing reads it at runtime, so the bake emits no module for it and the
    // `@plantry/engine/history` export path is gone.
    const result = bake({ dataDir: liveDataDir, outDir: liveOutDir });
    expect(existsSync(resolve(liveOutDir, "history.ts"))).toBe(false);
    expect(Object.keys(result)).not.toContain("historyPath");
  });

  it("emits a TypeScript module that imports schemas and exports the expected shape", () => {
    bake({ dataDir: liveDataDir, outDir: liveOutDir });

    const libraryText = readFileSync(resolve(liveOutDir, "library.ts"), "utf8");

    expect(libraryText).toContain('from "./schemas.js"');
    expect(libraryText).toContain("export const dishes: Dish[]");
    expect(libraryText).toContain("export const packSizes: PackSizeHeader[]");
    expect(libraryText).toContain("export const ingredients: Ingredient[]");
    expect(libraryText).toContain("export const catalog: CatalogIngredient[]");
    expect(libraryText).toContain("export const library:");
  });
});

describe("bake validator integration", () => {
  const fixtureRoot = resolve(tmpdir(), `plantry-bake-test-${process.pid}`);

  function writeFixture(
    dir: string,
    dishFile: { slug: string; body: string },
    historyExtra: string,
  ): { dataDir: string; outDir: string } {
    const dataDir = resolve(fixtureRoot, dir, "data");
    const outDir = resolve(fixtureRoot, dir, "out");
    const dishesDir = resolve(dataDir, "dishes");
    mkdirSync(dishesDir, { recursive: true });
    mkdirSync(outDir, { recursive: true });

    writeFileSync(resolve(dishesDir, `${dishFile.slug}.md`), dishFile.body);

    const ingredientsMd = [
      "# Ingredient Catalog",
      "",
      "| Ingredient | Group | Unit | Pack Size | Grams per piece | Protein /100g | Carbs /100g | Fat /100g | Fiber /100g | Special |",
      "|------------|-------|------|-----------|-----------------|---------------|-------------|-----------|-------------|---------|",
      "| Chicken | Proteins and Dairy | g | 500 g | | | | | | |",
      "",
    ].join("\n");
    writeFileSync(resolve(dataDir, "ingredients.md"), ingredientsMd);

    const historyMd = [
      "## Week of 2026-06-08",
      "",
      "| Week Start | Day | Meal | Dish Name | Dish ID |",
      "|------------|-----|------|-----------|---------|",
      "| 2026-06-08 | Monday | Lunch | Chicken masala gravy | 1 |",
      historyExtra,
      "",
    ].join("\n");
    writeFileSync(resolve(dataDir, "menu_history.md"), historyMd);

    return { dataDir, outDir };
  }

  const validDishFile = {
    slug: "chicken-masala-gravy",
    body: [
      "---",
      "id: 1",
      "name: Chicken masala gravy",
      "category: Gravy dish",
      "time: Lunch",
      "tags: [HP]",
      "primaryIngredient: Chicken",
      "preferred: Yes",
      "active: Yes",
      "satiety: High",
      "prepMinutes: 30",
      "seasons: All",
      "cuisine: Indian",
      "---",
      "",
      "## Ingredients",
      "",
      "| Ingredient | Quantity | Unit |",
      "|------------|----------|------|",
      "| Chicken | 400 | g |",
      "",
    ].join("\n"),
  };

  afterAll(() => {
    if (existsSync(fixtureRoot)) {
      rmSync(fixtureRoot, { recursive: true, force: true });
    }
  });

  it("fails when a history row references a dish id missing from the library", () => {
    const { dataDir, outDir } = writeFixture(
      "rejected-history",
      validDishFile,
      "| 2026-06-08 | Monday | Breakfast | Ghost dish | 999 |",
    );
    expect(() => bake({ dataDir, outDir })).toThrow(/dish id 999/);
  });

  it("fails when a dish ingredient row does not resolve to a catalog row", () => {
    const badDishFile = {
      slug: "chicken-masala-gravy",
      body: validDishFile.body.replace("| Chicken | 400 | g |", "| Phantom Spice | 5 | g |"),
    };
    const { dataDir, outDir } = writeFixture(
      "rejected-resolve",
      badDishFile,
      "| 2026-06-08 | Monday | Lunch | Chicken masala gravy | 1 |",
    );
    expect(() => bake({ dataDir, outDir })).toThrow(/Phantom Spice/);
  });

  it("fails when a dish file slug does not match its name", () => {
    const misnamed = { slug: "wrong-name", body: validDishFile.body };
    const { dataDir, outDir } = writeFixture(
      "rejected-slug",
      misnamed,
      "| 2026-06-08 | Monday | Lunch | Chicken masala gravy | 1 |",
    );
    expect(() => bake({ dataDir, outDir })).toThrow(/canonical slug is "chicken-masala-gravy"/);
  });
});
