import { describe, it, expect, beforeEach, afterAll } from "vitest";
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { tmpdir } from "node:os";
import { bake } from "../../scripts/bake.js";
import { parseDishes, parseMenuHistory } from "../../src/data/parse.js";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "../../..");
const liveDataDir = resolve(repoRoot, "data");
const liveOutDir = resolve(repoRoot, "engine/src/data");

function cleanLiveOutputs(): void {
  for (const file of ["library.ts", "history.ts"]) {
    const p = resolve(liveOutDir, file);
    if (existsSync(p)) rmSync(p);
  }
}

describe("bake against live data", () => {
  beforeEach(() => {
    cleanLiveOutputs();
  });
  afterAll(() => {
    cleanLiveOutputs();
  });

  it("emits library.ts and history.ts with matching counts", () => {
    const result = bake({ dataDir: liveDataDir, outDir: liveOutDir });

    expect(existsSync(result.libraryPath)).toBe(true);
    expect(existsSync(result.historyPath)).toBe(true);

    const libraryText = readFileSync(result.libraryPath, "utf8");
    const historyText = readFileSync(result.historyPath, "utf8");

    expect(libraryText.startsWith(
      "// Generated by engine/scripts/bake.ts from data/*.md. Do not edit by hand.",
    )).toBe(true);
    expect(historyText.startsWith(
      "// Generated by engine/scripts/bake.ts from data/*.md. Do not edit by hand.",
    )).toBe(true);

    const dishes = parseDishes(
      readFileSync(resolve(liveDataDir, "dishes.md"), "utf8"),
    );
    expect(result.dishCount).toBe(dishes.length);

    const history = parseMenuHistory(
      readFileSync(resolve(liveDataDir, "menu_history.md"), "utf8"),
    );
    expect(result.historyRowCount).toBe(history.length);
  });

  it("emits TypeScript modules that import schemas and export the expected shape", () => {
    bake({ dataDir: liveDataDir, outDir: liveOutDir });

    const libraryText = readFileSync(
      resolve(liveOutDir, "library.ts"),
      "utf8",
    );
    const historyText = readFileSync(
      resolve(liveOutDir, "history.ts"),
      "utf8",
    );

    expect(libraryText).toContain('from "./schemas.js"');
    expect(libraryText).toContain("export const dishes: Dish[]");
    expect(libraryText).toContain("export const packSizes: PackSizeHeader[]");
    expect(libraryText).toContain("export const ingredients: Ingredient[]");
    expect(libraryText).toContain("export const library:");

    expect(historyText).toContain('from "./schemas.js"');
    expect(historyText).toContain("export const history: MenuHistoryRow[]");
  });

});

describe("bake KNOWN_MISSING_DISH_IDS exception", () => {
  const fixtureRoot = resolve(tmpdir(), `plantry-bake-test-${process.pid}`);

  function writeFixture(dir: string, dishesMd: string, historyExtra: string): void {
    const dataDir = resolve(fixtureRoot, dir, "data");
    const outDir = resolve(fixtureRoot, dir, "out");
    mkdirSync(dataDir, { recursive: true });
    mkdirSync(outDir, { recursive: true });

    writeFileSync(resolve(dataDir, "dishes.md"), dishesMd);

    const ingredientsMd = [
      "# Pack sizes",
      "",
      "| Ingredient | Pack Size |",
      "|------------|-----------|",
      "| Chicken | 500 g |",
      "",
      "# Ingredients",
      "",
      "| Dish ID | Dish Name | Ingredient | Quantity | Unit |",
      "|---------|-----------|------------|----------|------|",
      "| 1 | Chicken masala gravy | Chicken | 400 | g |",
      "",
    ].join("\n");
    writeFileSync(resolve(dataDir, "ingredients.md"), ingredientsMd);

    const historyMd = [
      "## Week of 2026-06-08",
      "",
      "| Week Start | Day | Meal | Dish Name | Dish ID |",
      "|------------|-----|------|-----------|---------|",
      "| 2026-06-08 | Monday | Lunch | Chicken masala gravy | 1 |",
      historyExtra,
      "",
    ].join("\n");
    writeFileSync(resolve(dataDir, "menu_history.md"), historyMd);
  }

  const dishesMd = [
    "# Dishes",
    "",
    "| ID | Name | Category | Time | Tags | Primary Ingredient | Preferred | Active | Satiety | Prep Min | Seasons |",
    "|----|------|----------|------|------|--------------------|-----------|--------|---------|----------|---------|",
    "| 1 | Chicken masala gravy | Gravy dish | Lunch | HP | Chicken | Yes | Yes | High | 30 | All |",
    "",
  ].join("\n");

  afterAll(() => {
    if (existsSync(fixtureRoot)) {
      rmSync(fixtureRoot, { recursive: true, force: true });
    }
  });

  it("succeeds when only known-missing dish id 7 is referenced from history", () => {
    writeFixture(
      "allowed",
      dishesMd,
      "| 2026-06-08 | Monday | Breakfast | Rajma | 7 |",
    );
    const dataDir = resolve(fixtureRoot, "allowed/data");
    const outDir = resolve(fixtureRoot, "allowed/out");
    expect(() => bake({ dataDir, outDir })).not.toThrow();
    expect(existsSync(resolve(outDir, "library.ts"))).toBe(true);
    expect(existsSync(resolve(outDir, "history.ts"))).toBe(true);
  });

  it("fails when an unknown missing dish id is referenced from history", () => {
    writeFixture(
      "rejected",
      dishesMd,
      "| 2026-06-08 | Monday | Breakfast | Ghost dish | 999 |",
    );
    const dataDir = resolve(fixtureRoot, "rejected/data");
    const outDir = resolve(fixtureRoot, "rejected/out");
    expect(() => bake({ dataDir, outDir })).toThrow(/dish id 999/);
  });
});
